### ISSUE TITLE
libmpv

### ISSUE THREAD

**Issue by xedsvg** [aykevl93/plaincast#1]
How can I disable libmpv and send the links somewhere else?
I want to integrate it in MagicMirror2 via a html5 audio player.

**Comment by aykevl** [comment]
What you can do, is create a new player backend (see `apps/youtube/mp/backend.go`) and use it in `apps/youtube/mp/player.go`, function `New`.
If it is configurable at build time (via build tags), I will consider merging the patches.

Does that answer your question?

**Comment by aykevl** [comment]
Btw, have you ever visited https://www.youtube.com/tv? That might be of interest to you. That is the system I'm emulating, mostly.

**Comment by xedsvg** [comment]
I know about https://www.youtube.com/tv :smile: . There is a nodejs package (peer-dial) that spawns a browser to https://www.youtube.com/tv?pairCode= but you do not have control over volume or track info. I tried to modify peer-dial so it will work as your app (as it's more simple for me to work in js) but it does not return the screen_id or access_type.

**Comment by xedsvg** [comment]
I think I'll just implement a socket.io client/server as a player backend. This way I can play/control from a variety of modules.

**Comment by aykevl** [comment]
As simply sending the links somewhere else is not how this player is intended to work, I'll close this issue. Plaincast must be able to pause/play/seek the current video.
