### ISSUE TITLE
Error on linking and attempting to play video

### ISSUE THREAD

**Issue by mixedCase** [aykevl93/plaincast#2]
Using youtube-dl 2017.01.24, mpv 0.23.0 and Go 1.7.4 linux/amd64.

YouTube Android app detects server correctly, but on linking I get the following:

```
  File "<string>", line 24
    except DownloadError, why:
                        ^
SyntaxError: invalid syntax
```

Despite that, Android works as if everything was okay and plaincast soldiers on. When attempting to play video, I get `03:25:14.576 [player] could not grab video:EOF`.

**Comment by aykevl** [comment]
Which Python version are you using?
