### ISSUE TITLE
Google Play Music

### ISSUE THREAD

**Issue by dougmoscrop** [aykevl93/plaincast#8]
Have you had experience with Google Play Music as to whether or not it uses DIAL or needs castv2?

**Comment by aykevl** [comment]
I think I looked into it once, but IIRC it requires castv2.
Also, I'm not actively developing this project anymore so anything besides YouTube is probably out of scope - unless someone actually manages to write code for it.

**Comment by dougmoscrop** [comment]
Understood, thanks.

**Comment by Enelar** [comment]
@aykevl Can you please explain how to cast youtube from my smartphone.
The button isn't appearing, however server is running. Does it supposed to pop up as regular chrome cast device, right?

**Comment by aykevl** [comment]
I just tested and it definitely works for me. Are you sure you're on the same network?
Also, you may need to run the server on a computer that's on a wired connection - at least that's the case with the WiFi where I'm running it.

Note that this only works for YouTube, not for Google Play Music.
